;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        indent-for-tab-command
        kill-region
        repeat
        rjsx-delete-creates-full-tag
        tabbar-backward-tab
        ))

(setq mc/cmds-to-run-once
      '(
        comint-delchar-or-maybe-eof
        comment-dwim
        find-file
        js2-mode-hide-element
        scroll-down-line
        scroll-up-line
        suspend-frame
        ))
